target_reacher: # this has to match your node Name
  ros__parameters:
    aruco_target:
      x: 6.5
      y: 5.0
    final_destination:
      # "origin1", "origin2", "origin3", "origin4"
      frame_id: "origin1"
      aruco_0:
        x: 1.0
        y: 1.0
      aruco_1:
        x: 1.0
        y: -1.0
      aruco_2:
        x: -1.0
        y: -1.0
      aruco_3:
        x: -1.0
        y: 1.0